import Head from 'next/head'
import Image from 'next/image'
import { getSession, useSession, signIn, signOut } from "next-auth/react"
import { useRouter } from 'next/router'

import styles from '../../styles/Home.module.css'

export default function Team({ session }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Billing</h1>
			</main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)
	const { projectShortCode } = context.query

	// TODO - check if projectShortCode exists

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  return {
    props: { session, projectShortCode }
  }
}
