web:
    image: shaneburkhart/construction-vr-demo
    ports:
        - "3000:4567"
    links:
        - redis
    volumes:
        - .:/app
    env_file:
        - user.env
    command: "rerun --background ruby server.rb"

web_prod:
    image: shaneburkhart/construction-vr-demo
    ports:
        - "4567:4567"
    links:
        - redis
    volumes:
        - .:/app
    env_file:
        - user.env
    command: "ruby server.rb"

redis:
    image: redis:3.2
