web:
    image: shaneburkhart/construction-vr-demo
    links:
        - pg
        - redis
    volumes:
        - .:/app
    env_file:
        - user.env
    command: "rerun --ignore react/* --ignore public/* --background ruby server.rb"

websocket:
    image: shaneburkhart/construction-vr-demo
    links:
        - pg
        - redis
    volumes:
        - .:/app
    env_file:
        - user.env
    command: "rerun --pattern common/* --pattern models/* --pattern websocket.js --background node websocket.js"

react_build:
    image: shaneburkhart/construction-vr-demo
    volumes:
        - .:/app
    command: "npm run watch"

jest_tests:
    image: shaneburkhart/construction-vr-demo
    links:
        - pg
        - redis
    volumes:
        - .:/app
    env_file:
        - user.env
    command: "true"

pg:
    image: postgres
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=mydb
    volumes:
        - ./data/pg:/var/lib/postgresql/data

testing_worker:
    image: shaneburkhart/construction-vr-demo
    volumes:
        - .:/app
    env_file:
        - user.env
    command: "ruby workers/skp_model_tester.rb"

notification_worker:
    image: shaneburkhart/construction-vr-demo
    volumes:
        - .:/app
    env_file:
        - user.env
    command: "ruby workers/skp_rendering_notification.rb"

redis:
    image: redis:3.2
    command: "redis-server --save '' --appendonly no"

nginx:
    image: nginx:1.17
    ports:
        - "3000:3000"
    volumes:
        - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    links:
        - web
        - websocket
