web:
    image: shaneburkhart/construction-vr-demo-web
    links:
        - pg
        - redis
    volumes:
        - ./packages/web:/app
    env_file:
        - user.env
    command: "rerun --ignore react/* --ignore public/* --background ruby server.rb"

websocket:
    image: shaneburkhart/construction-vr-demo-web
    links:
        - pg
        - redis
    volumes:
        - ./packages/web:/app
    env_file:
        - user.env
    # command: "rerun --pattern common/* --pattern controllers/* --pattern websocket.js --background node websocket.js"
    command: "npx nodemon -w websocket.js -w common/* -w controllers/* -w models/* -w util/* -w constants/*"

react_build:
    image: shaneburkhart/construction-vr-demo-web
    volumes:
        - ./packages/web:/app
    command: "npm run watch"

pg:
    image: postgres:10
    # ports:
        # - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=mydb
    volumes:
        - ./data/pg:/var/lib/postgresql/data

redis:
    image: redis:3.2
    command: "redis-server --save '' --appendonly no"

nginx:
    image: nginx:1.17
    ports:
        - "3001:3000"
    volumes:
        - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    links:
        - web
        - websocket
