version: "3.9"

services: 
    web:
        image: shaneburkhart/finish-vision-show-web
        ports: [ "127.0.0.1:3001:3000" ] 
        networks: [ pg, redis ]
        env_file:
            - user.env
        command: "npm run prod"

    pg:
        image: postgres:10
        networks: [ pg ]
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=mydb
        volumes:
            - ./data/pg:/var/lib/postgresql/data

    redis:
        image: redis:3.2
        networks: [ redis ]
        command: "redis-server --save '' --appendonly no"

networks:
    redis:
    pg:
