web:
    image: shaneburkhart/construction-vr-demo-web
    links:
        - pg
        - redis
    env_file:
        - user.env
    command: "ruby server.rb"

websocket:
    image: shaneburkhart/construction-vr-demo-web
    links:
        - pg
        - redis
    env_file:
        - user.env
    command: "node websocket.js"

pg:
    image: postgres:10
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=mydb
    ports:
        - "5432:5432"
    volumes:
        - ./data/pg:/var/lib/postgresql/data

redis:
    image: redis:3.2
    command: "redis-server --save '' --appendonly no"

nginx:
    image: nginx:1.17
    ports:
        - "3001:80"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
        - web
        - websocket