export default {
  FULL_UPDATE: "FULL_UPDATE",
  EACH_UPDATE: "EACH_UPDATE",
  SERVER_UPDATE: "SERVER_UPDATE",
  UPDATE_MODAL: "UPDATE_MODAL",
  REORDER_CATEGORIES: "REORDER_CATEGORIES",
  MOVE_SELECTION: "MOVE_SELECTION",
  MOVE_OPTION: "MOVE_OPTION",
  UPDATE_FILTER: "UPDATE_FILTER",
  CLEAN_NEW: "CLEAN_NEW",
}
