export default {
  FULL_UPDATE: "FULL_UPDATE",
  EACH_UPDATE: "EACH_UPDATE",
  REORDER_CATEGORIES: "REORDER_CATEGORIES",
  MOVE_SELECTION: "MOVE_SELECTION",
  MOVE_OPTION: "MOVE_OPTION",
  UPDATE_FILTER: "UPDATE_FILTER",
}
