export default {
  LOADING: "LOADING",
  UPDATE_PROJECT: "UPDATE_PROJECT",

  UPDATE_SEARCH_RESULTS: "UPDATE_SEARCH_RESULTS",
  CLEAR_SEARCH_RESULTS: "CLEAR_SEARCH_RESULTS",

  ADD_SELECTION: "ADD_SELECTION",
  REMOVE_SELECTION: "REMOVE_SELECTION",

  UNLINK_OPTION: "UNLINK_OPTION",

  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
}
