module.exports = {
  EXECUTE_CLIENT_EVENT: "EXECUTE_CLIENT_EVENT",

  ADD_NEW_OPTION: "ADD_NEW_OPTION",
  ADD_NEW_SELECTION: "ADD_NEW_SELECTION",
  ADD_NEW_CATEGORY: "ADD_NEW_CATEGORY",

  REMOVE_OPTION: "REMOVE_OPTION",
  REMOVE_SELECTION: "REMOVE_SELECTION",
  REMOVE_CATEGORY: "REMOVE_CATEGORY",

  UPDATE_OPTION: "UPDATE_OPTION",
  UPDATE_SELECTION: "UPDATE_SELECTION",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  UPDATE_PROJECT: "UPDATE_PROJECT",

  ALPHABETIZE_SELECTIONS: "ALPHABETIZE_SELECTIONS",

  MOVE_OPTION: "MOVE_OPTION",
  MOVE_SELECTION: "MOVE_SELECTION",
  MOVE_CATEGORY: "MOVE_CATEGORY",

  BATCH_UPDATE_OPTIONS: "BATCH_UPDATE_OPTIONS",
  BATCH_UPDATE_SELECTIONS: "BATCH_UPDATE_SELECTIONS",
  BATCH_UPDATE_CATEGORIES: "BATCH_UPDATE_CATEGORIES",

  FULL_UPDATE: "FULL_UPDATE",
  EACH_UPDATE: "EACH_UPDATE",
  SERVER_UPDATE: "SERVER_UPDATE",
  UPDATE_MODAL: "UPDATE_MODAL",
  REORDER_CATEGORIES: "REORDER_CATEGORIES",
  UPDATE_FILTERS: "UPDATE_FILTERS",
  CLEAN_NEW: "CLEAN_NEW",
}

