module.exports = {
  EXECUTE_CLIENT_EVENT: "EXECUTE_CLIENT_EVENT",
  ADD_NEW_SELECTION: "ADD_NEW_SELECTION",
  ADD_NEW_CATEGORY: "ADD_NEW_CATEGORY",

  REMOVE_SELECTION: "REMOVE_SELECTION",
  REMOVE_CATEGORY: "REMOVE_CATEGORY",

  UPDATE_SELECTION: "UPDATE_SELECTION",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",

  FULL_UPDATE: "FULL_UPDATE",
  EACH_UPDATE: "EACH_UPDATE",
  SERVER_UPDATE: "SERVER_UPDATE",
  UPDATE_MODAL: "UPDATE_MODAL",
  REORDER_CATEGORIES: "REORDER_CATEGORIES",
  MOVE_SELECTION: "MOVE_SELECTION",
  MOVE_OPTION: "MOVE_OPTION",
  UPDATE_FILTER: "UPDATE_FILTER",
  CLEAN_NEW: "CLEAN_NEW",
}

